name: GitHub Actions Cypress/cucumber/Telnyx
on:
    push:
        branches: [master]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run smoke
        uses: cypress-io/github-action@v2
        with:
            config-file: cypress.smoke.config.js
            browser: electron
      - name: Create Report
        if: always()
        run: npm run allure:generate
      - name: Upload artifact allure-report
        uses: actions/upload-artifact@v1
        if: always()
        with:
            name: allure-report
            path: ./allure-report
      - name: Deploy to pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_branch: gh-pages
            publish_dir: reports