name: GitHub Actions Cypress/cucumber/Telnyx
on:
    push:
        branches: [master]
permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run smoke
        uses: cypress-io/github-action@v2
        with:
            config-file: cypress.smoke.config.js
            browser: electron
      - name: Create Report
        if: always()
        run: npm run allure:generate
      - name: Upload artifact allure-report
        uses: actions/upload-artifact@v1
        if: always()
        with:
            name: allure-report
            path: ./allure-report
      - name: Deploy report
        uses: JamesIves/github-pages-deploy-action@3.1.0
        if: always()
        with:
            ACCESS_TOKEN: ${{'secrets.ACCESS_TOKEN'}}
            BRANCH: master # The branch the action should deploy to.
            FOLDER: allure-report # The folder the action should deploy.
            TARGET_FOLDER: docs